baseURL = 'https://getpid.dev/'
languageCode = 'en-us'
title = 'getpid.dev'
theme = 'papermod'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[[menu.main]]
name = "🏠"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "How-tos"
url = "/howto/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "Search"
url = "/search/"
weight = 5

# JSON necessary for search
[outputs]
    home = ['html', 'rss', 'json'] 

[params]
showReadingTime = true
defaultTheme = 'auto'
mainSections = ['blog', 'howto']
    
    [params.homeInfoParams]
        Title = 'Hi there 👋'
        Content = """This is a personal blog where I share my knowledge and experiences about software development, Go programming, and more.
Feel free to connect with me on [GitHub](https://github.com/dmksnnk) or [LinkedIn](http://www.linkedin.com/in/dmytro-kasianenko/)."""
    [[params.socialIcons]]
        name = 'github'
        url = 'https://github.com/dmksnnk'
    [[params.socialIcons]]
        name = 'linkedin'
        url = 'http://www.linkedin.com/in/dmytro-kasianenko/'
